### PR TITLE
BUGFIX: changing comparison so backends can be created

### PR DESCRIPTION
**Pull request by marcosalcazar**

### CODE REVIEW

**Comment by scdoshi** [comment]
Good find. The problem is that post_syncdb sends the module object as the 'app' argument, and post_migrate (South) sends the app name string as the 'app' argument. I was testing only with South, and forgot to test the plain syncdb scenario.

Given that, your change should still not fix the issue completely. I am pushing a fix, should be up in a bit. Can you confirm that it solves the problem?

**Comment by scdoshi** [comment]
Ok, should be fixed on master commit SHA 4123f3164c14124843c34f6e52fcea885ab0e15e. I did try it without South as well, but please test and if there are no new issues with the fix, I will update the version number and push to pypi as well

**Comment by marcosalcazar** [comment]
Works perfect for me now. Sorry for the confuson, but we are not using South for the moment. I can confirm that Backends are being created now. BTW, I'm having this exception just before "syncdb" ends:

<pre>
Exception AttributeError: AttributeError("'NoneType' object has no attribute 'utf_8_decode'",) in <bound method Signal._remove_receiver of <django.dispatch.dispatcher.Signal object at 0x1422690>> ignored
</pre>

I haven't seen that error before, and everything seems to be ok now.

Thanks for everything, Marcos

**Comment by scdoshi** [comment]
OK great. I tried running the demo app without south (just syncdb) and can't reproduce the error.

Found this python bug report with a google search, but it doesn't lead to any definite conclusions. http://bugs.python.org/issue14847

I'm closing this ticket for now. If the error persists and you think it is related to notifier, open another ticket.

**Pull request closed without merging**
